#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  traefikElbId: "SET_BY_TERRAFORM"
  rootDomain: "SET_BY_TERRAFORM"
  basicAuthPassword: "SET_BY_TERRAFORM"
global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingressRoute.adminDomain: "admin.{{.Values.projectValues.rootDomain}}"
      ingressRoute.rootDomain: "{{.Values.projectValues.rootDomain}}"
charts:
  argocd-config:
    namespace: argocd
    targetRevision: 0.5.0
    parameters:
      ingressRoute.certificate.enabled: "true"
      ingressRoute.entryPointName: "websecure"
  traefik:
    namespace: routing
    targetRevision: 21.0.0
    # Overrides default Helm Parameters
    parameters:
      "traefik.deployment.replicas": "1"
      "traefik.service.annotations.kubernetes\\.io\\/elb\\.id": "{{.Values.projectValues.traefikElbId}}"
  cert-manager:
    namespace: cert-manager
    targetRevision: 0.3.0
    parameters:
      clusterIssuer.http.email: "my-mail@mail.com"
  basic-auth-gateway:
    namespace: routing
    targetRevision: 0.6.1
    parameters:
      ingressRoute.domain: "admin.{{.Values.projectValues.rootDomain}}"
      credentials.password: "{{.Values.projectValues.basicAuthPassword}}"
  kafka:
    namespace: kafka
    targetRevision: 22.1.5
    parameters:
      "kafka.replicaCount": "1"
  akhq:
    namespace: kafka
    targetRevision: 0.24.0
  # Override values with local values file
  iits-admin-dashboard-nginx:
    namespace: admin
    targetRevision: 1.2.3
  elastic-stack:
    namespace: monitoring
    targetRevision: 7.17.3-otc-volumes
    adminDomain: "admin.{{.Values.projectValues.rootDomain}}"
    parameters:
      elasticsearch.replicas: 1
  kasm:
    namespace: kasm
    targetRevision: 0.1.1
    parameters:
      services.firstuser.extraEnv.VNC_PW: "6upWDZ2DQwsmz,S%Eys,qmfE9GlpwuQy"
      services.firstuser.ingressRoute.domain: "firstuser.{{.Values.projectValues.rootDomain}}"
